language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database jobbr;' -U postgres
  - psql -c 'create database test_jobbr;' -U postgres
  - python manage.py db upgrade
  - yarn
  - webpack -p
install: "pip install -r requirements.txt"
script: python -m unittest