language: python
python:
  - "3.6"
sudo: required
node_js:
  - "4.3"
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
services:
  - postgresql
before_script:
  - psql -c 'create database jobbr;' -U postgres
  - psql -c 'create database test_jobbr;' -U postgres
  - python manage.py db upgrade
  - yarn
  - webpack -p
install: "pip install -r requirements.txt"
script: python -m unittest