language: python
python:
  - "3.6"
sudo: required
env:
  - NODE_JS_VERSION=4.3
script:
node_js:
  - "4.3"
cache:
  yarn: true
services:
  - postgresql
before_script:
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh # update nvm
  - bash -c "nvm use $NODE_JS_VERSION" || true
  - bash -c "source ~/.nvm/nvm.sh; nvm install $NODE_JS_VERSION; node --version"
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - psql -c 'create database jobbr;' -U postgres
  - psql -c 'create database test_jobbr;' -U postgres
  - python manage.py db upgrade
  - yarn
  - webpack -p
install: "pip install -r requirements.txt"
script: python -m unittest