"""empty message

Revision ID: 0d98d3b9aab9
Revises: 47f3a9401a9a
Create Date: 2017-05-27 09:27:54.101286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d98d3b9aab9'
down_revision = '47f3a9401a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_application_date'), 'application', ['application_date'], unique=False)
    op.create_index(op.f('ix_application_created'), 'application', ['created'], unique=False)
    op.create_index(op.f('ix_application_deleted'), 'application', ['deleted'], unique=False)
    op.create_index(op.f('ix_application_updated'), 'application', ['updated'], unique=False)
    op.create_index(op.f('ix_application_contact_created'), 'application_contact', ['created'], unique=False)
    op.create_index(op.f('ix_application_contact_deleted'), 'application_contact', ['deleted'], unique=False)
    op.create_index(op.f('ix_application_contact_email'), 'application_contact', ['email'], unique=False)
    op.create_index(op.f('ix_application_contact_first_name'), 'application_contact', ['first_name'], unique=False)
    op.create_index(op.f('ix_application_contact_last_name'), 'application_contact', ['last_name'], unique=False)
    op.create_index(op.f('ix_application_contact_phone_number'), 'application_contact', ['phone_number'], unique=False)
    op.create_index(op.f('ix_application_contact_position'), 'application_contact', ['position'], unique=False)
    op.create_index(op.f('ix_application_contact_updated'), 'application_contact', ['updated'], unique=False)
    op.add_column('application_event', sa.Column('event_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_application_event_created'), 'application_event', ['created'], unique=False)
    op.create_index(op.f('ix_application_event_deleted'), 'application_event', ['deleted'], unique=False)
    op.create_index(op.f('ix_application_event_event_time'), 'application_event', ['event_time'], unique=False)
    op.create_index(op.f('ix_application_event_updated'), 'application_event', ['updated'], unique=False)
    op.drop_column('application_event', 'application_notes')
    op.create_index(op.f('ix_keyword_created'), 'keyword', ['created'], unique=False)
    op.create_index(op.f('ix_keyword_deleted'), 'keyword', ['deleted'], unique=False)
    op.create_index(op.f('ix_keyword_updated'), 'keyword', ['updated'], unique=False)
    op.create_index(op.f('ix_position_accomplishment_created'), 'position_accomplishment', ['created'], unique=False)
    op.create_index(op.f('ix_position_accomplishment_deleted'), 'position_accomplishment', ['deleted'], unique=False)
    op.create_index(op.f('ix_position_accomplishment_updated'), 'position_accomplishment', ['updated'], unique=False)
    op.create_index(op.f('ix_resume_position_created'), 'resume_position', ['created'], unique=False)
    op.create_index(op.f('ix_resume_position_deleted'), 'resume_position', ['deleted'], unique=False)
    op.create_index(op.f('ix_resume_position_position_end_date'), 'resume_position', ['position_end_date'], unique=False)
    op.create_index(op.f('ix_resume_position_position_start_date'), 'resume_position', ['position_start_date'], unique=False)
    op.create_index(op.f('ix_resume_position_updated'), 'resume_position', ['updated'], unique=False)
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_deleted'), 'user', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_updated'), 'user', ['updated'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_index(op.f('ix_resume_position_updated'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_position_start_date'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_position_end_date'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_deleted'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_created'), table_name='resume_position')
    op.drop_index(op.f('ix_position_accomplishment_updated'), table_name='position_accomplishment')
    op.drop_index(op.f('ix_position_accomplishment_deleted'), table_name='position_accomplishment')
    op.drop_index(op.f('ix_position_accomplishment_created'), table_name='position_accomplishment')
    op.drop_index(op.f('ix_keyword_updated'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_deleted'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_created'), table_name='keyword')
    op.add_column('application_event', sa.Column('application_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_application_event_updated'), table_name='application_event')
    op.drop_index(op.f('ix_application_event_event_time'), table_name='application_event')
    op.drop_index(op.f('ix_application_event_deleted'), table_name='application_event')
    op.drop_index(op.f('ix_application_event_created'), table_name='application_event')
    op.drop_column('application_event', 'event_notes')
    op.drop_index(op.f('ix_application_contact_updated'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_position'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_phone_number'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_last_name'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_first_name'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_email'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_deleted'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_created'), table_name='application_contact')
    op.drop_index(op.f('ix_application_updated'), table_name='application')
    op.drop_index(op.f('ix_application_deleted'), table_name='application')
    op.drop_index(op.f('ix_application_created'), table_name='application')
    op.drop_index(op.f('ix_application_application_date'), table_name='application')
    # ### end Alembic commands ###
