"""empty message

Revision ID: 652ff7fda4d7
Revises:
Create Date: 2017-05-12 20:22:07.747709

"""
from alembic import op
import sqlalchemy as sa
import social_sqlalchemy


# revision identifiers, used by Alembic.
revision = '652ff7fda4d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_auth_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=True),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('issued', sa.Integer(), nullable=True),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.Column('assoc_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_url', 'handle')
    )
    op.create_table('social_auth_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'email')
    )
    op.create_index(op.f('ix_social_auth_code_code'), 'social_auth_code', ['code'], unique=False)
    op.create_table('social_auth_nonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('salt', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_url', 'timestamp', 'salt')
    )
    op.create_table('social_auth_partial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('data', social_sqlalchemy.storage.JSONType(), nullable=True),
    sa.Column('next_step', sa.Integer(), nullable=True),
    sa.Column('backend', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_auth_partial_token'), 'social_auth_partial', ['token'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('application_notes', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_company_name'), 'application', ['company_name'], unique=False)
    op.create_index(op.f('ix_application_position'), 'application', ['position'], unique=False)
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='keyword_user_unique')
    )
    op.create_index(op.f('ix_keyword_keyword'), 'keyword', ['keyword'], unique=False)
    op.create_table('resume_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('position_start_date', sa.DateTime(), nullable=False),
    sa.Column('position_end_date', sa.DateTime(), nullable=True),
    sa.Column('position_start_title', sa.String(length=255), nullable=True),
    sa.Column('starting_salary', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('salary_rate', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_position_company_name'), 'resume_position', ['company_name'], unique=False)
    op.create_index(op.f('ix_resume_position_position_start_title'), 'resume_position', ['position_start_title'], unique=False)
    op.create_index(op.f('ix_resume_position_position_title'), 'resume_position', ['position_title'], unique=False)
    op.create_index(op.f('ix_resume_position_salary'), 'resume_position', ['salary'], unique=False)
    op.create_index(op.f('ix_resume_position_starting_salary'), 'resume_position', ['starting_salary'], unique=False)
    op.create_table('social_auth_usersocialauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('extra_data', social_sqlalchemy.storage.JSONType(), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_auth_usersocialauth_user_id'), 'social_auth_usersocialauth', ['user_id'], unique=False)
    op.create_table('application_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('contact_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.String(length=255), nullable=False),
    sa.Column('application_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_event_event_description'), 'application_event', ['event_description'], unique=False)
    op.create_index(op.f('ix_application_event_event_type'), 'application_event', ['event_type'], unique=False)
    op.create_table('application_keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE')
    )
    op.create_table('position_accomplishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['resume_position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accomplishment_keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('accomplishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accomplishment_id'], ['position_accomplishment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE')
    )
    op.create_table('event_contacts',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['application_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['application_event.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_contacts')
    op.drop_table('accomplishment_keyword')
    op.drop_table('position_accomplishment')
    op.drop_table('application_keyword')
    op.drop_index(op.f('ix_application_event_event_type'), table_name='application_event')
    op.drop_index(op.f('ix_application_event_event_description'), table_name='application_event')
    op.drop_table('application_event')
    op.drop_table('application_contact')
    op.drop_index(op.f('ix_social_auth_usersocialauth_user_id'), table_name='social_auth_usersocialauth')
    op.drop_table('social_auth_usersocialauth')
    op.drop_index(op.f('ix_resume_position_starting_salary'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_salary'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_position_title'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_position_start_title'), table_name='resume_position')
    op.drop_index(op.f('ix_resume_position_company_name'), table_name='resume_position')
    op.drop_table('resume_position')
    op.drop_index(op.f('ix_keyword_keyword'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_application_position'), table_name='application')
    op.drop_index(op.f('ix_application_company_name'), table_name='application')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_index(op.f('ix_social_auth_partial_token'), table_name='social_auth_partial')
    op.drop_table('social_auth_partial')
    op.drop_table('social_auth_nonce')
    op.drop_index(op.f('ix_social_auth_code_code'), table_name='social_auth_code')
    op.drop_table('social_auth_code')
    op.drop_table('social_auth_association')
    # ### end Alembic commands ###
